# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ophelia/Documents/Hardis-Blockchain/ui/mainwindow.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(845, 568)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.type_txt = QtWidgets.QComboBox(self.centralwidget)
        self.type_txt.setGeometry(QtCore.QRect(210, 150, 191, 31))
        self.type_txt.setObjectName("type_txt")
        self.type_txt.addItem("")
        self.type_txt.addItem("")
        self.type_txt.addItem("")
        self.type_txt.addItem("")
        self.type_txt.addItem("")
        self.Titre = QtWidgets.QLabel(self.centralwidget)
        self.Titre.setGeometry(QtCore.QRect(160, 20, 561, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.Titre.setFont(font)
        self.Titre.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.Titre.setFrameShadow(QtWidgets.QFrame.Plain)
        self.Titre.setTextFormat(QtCore.Qt.AutoText)
        self.Titre.setAlignment(QtCore.Qt.AlignCenter)
        self.Titre.setObjectName("Titre")
        self.Type = QtWidgets.QLabel(self.centralwidget)
        self.Type.setGeometry(QtCore.QRect(50, 140, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Type.setFont(font)
        self.Type.setObjectName("Type")
        self.BU = QtWidgets.QLabel(self.centralwidget)
        self.BU.setGeometry(QtCore.QRect(480, 140, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.BU.setFont(font)
        self.BU.setObjectName("BU")
        self.BU_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.BU_txt.setGeometry(QtCore.QRect(600, 150, 191, 31))
        self.BU_txt.setObjectName("BU_txt")
        self.Equipe_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.Equipe_txt.setGeometry(QtCore.QRect(600, 210, 191, 31))
        self.Equipe_txt.setText("")
        self.Equipe_txt.setObjectName("Equipe_txt")
        self.Equipe = QtWidgets.QLabel(self.centralwidget)
        self.Equipe.setGeometry(QtCore.QRect(480, 200, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Equipe.setFont(font)
        self.Equipe.setObjectName("Equipe")
        self.Marque_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.Marque_txt.setGeometry(QtCore.QRect(210, 210, 191, 31))
        self.Marque_txt.setObjectName("Marque_txt")
        self.Marque = QtWidgets.QLabel(self.centralwidget)
        self.Marque.setGeometry(QtCore.QRect(50, 200, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Marque.setFont(font)
        self.Marque.setObjectName("Marque")
        self.NoSerie_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.NoSerie_txt.setGeometry(QtCore.QRect(210, 270, 191, 31))
        self.NoSerie_txt.setObjectName("NoSerie_txt")
        self.NoSerie = QtWidgets.QLabel(self.centralwidget)
        self.NoSerie.setGeometry(QtCore.QRect(50, 260, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.NoSerie.setFont(font)
        self.NoSerie.setObjectName("NoSerie")
        self.DateAchat = QtWidgets.QLabel(self.centralwidget)
        self.DateAchat.setGeometry(QtCore.QRect(50, 320, 161, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.DateAchat.setFont(font)
        self.DateAchat.setObjectName("DateAchat")
        self.Responsable_txt = QtWidgets.QLineEdit(self.centralwidget)
        self.Responsable_txt.setGeometry(QtCore.QRect(600, 270, 191, 31))
        self.Responsable_txt.setText("")
        self.Responsable_txt.setObjectName("Responsable_txt")
        self.Responsable = QtWidgets.QLabel(self.centralwidget)
        self.Responsable.setGeometry(QtCore.QRect(480, 260, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Responsable.setFont(font)
        self.Responsable.setObjectName("Responsable")
        self.Date = QtWidgets.QDateEdit(self.centralwidget)
        self.Date.setGeometry(QtCore.QRect(210, 330, 191, 31))
        self.Date.setAutoFillBackground(False)
        self.Date.setCalendarPopup(False)
        self.Date.setDate(QtCore.QDate(2018, 5, 23))
        self.Date.setObjectName("Date")
        self.Enregistrer = QtWidgets.QPushButton(self.centralwidget)
        self.Enregistrer.setGeometry(QtCore.QRect(250, 460, 321, 41))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.Enregistrer.setFont(font)
        self.Enregistrer.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Enregistrer.setMouseTracking(False)
        self.Enregistrer.setFlat(False)
        self.Enregistrer.setObjectName("Enregistrer")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(10, 10, 131, 71))
        self.logo.setMaximumSize(QtCore.QSize(282, 160))
        self.logo.setSizeIncrement(QtCore.QSize(1, 2))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 845, 22))
        self.menubar.setObjectName("menubar")
        self.menuHardis_Mat_riel = QtWidgets.QMenu(self.menubar)
        self.menuHardis_Mat_riel.setObjectName("menuHardis_Mat_riel")
        self.menuEnregistrer_mat_riel = QtWidgets.QMenu(self.menubar)
        self.menuEnregistrer_mat_riel.setObjectName("menuEnregistrer_mat_riel")
        self.menuD_placement_mat_riel = QtWidgets.QMenu(self.menubar)
        self.menuD_placement_mat_riel.setObjectName("menuD_placement_mat_riel")
        self.menuConsulter_mat_riel = QtWidgets.QMenu(self.menubar)
        self.menuConsulter_mat_riel.setObjectName("menuConsulter_mat_riel")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuHardis_Mat_riel.menuAction())
        self.menubar.addAction(self.menuEnregistrer_mat_riel.menuAction())
        self.menubar.addAction(self.menuD_placement_mat_riel.menuAction())
        self.menubar.addAction(self.menuConsulter_mat_riel.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "HARDIS Matériel"))
        self.type_txt.setItemText(0, _translate("MainWindow", "Ordinateur et accessoires"))
        self.type_txt.setItemText(1, _translate("MainWindow", "Bureau"))
        self.type_txt.setItemText(2, _translate("MainWindow", "Chaise"))
        self.type_txt.setItemText(3, _translate("MainWindow", "Micro-ondes"))
        self.type_txt.setItemText(4, _translate("MainWindow", "Cafetière"))
        self.Titre.setText(_translate("MainWindow", "Enregistrer un nouvel équipement"))
        self.Type.setText(_translate("MainWindow", "Type de matériel"))
        self.BU.setText(_translate("MainWindow", "BU"))
        self.Equipe.setText(_translate("MainWindow", "Equipe"))
        self.Marque.setText(_translate("MainWindow", "Marque"))
        self.NoSerie.setText(_translate("MainWindow", "Numéro de série"))
        self.DateAchat.setText(_translate("MainWindow", "Date d\'achat"))
        self.Responsable.setText(_translate("MainWindow", "Personne\n"
"responsable"))
        self.Enregistrer.setText(_translate("MainWindow", "Enregistrer"))
        self.menuHardis_Mat_riel.setTitle(_translate("MainWindow", "Hardis Matériel"))
        self.menuEnregistrer_mat_riel.setTitle(_translate("MainWindow", "Enregistrer matériel"))
        self.menuD_placement_mat_riel.setTitle(_translate("MainWindow", "Déplacement matériel"))
        self.menuConsulter_mat_riel.setTitle(_translate("MainWindow", "Consulter matériel"))

