# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '/home/ophelia/Documents/Qt_Projets/Appli/query.ui'
#
# Created by: PyQt5 UI code generator 5.5.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Accueil(object):
    def setupUi(self, Accueil):
        Accueil.setObjectName("Accueil")
        Accueil.resize(845, 568)
        self.centralwidget = QtWidgets.QWidget(Accueil)
        self.centralwidget.setObjectName("centralwidget")
        self.Title = QtWidgets.QLabel(self.centralwidget)
        self.Title.setGeometry(QtCore.QRect(180, 30, 561, 71))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.Title.setFont(font)
        self.Title.setObjectName("Title")
        self.logo = QtWidgets.QLabel(self.centralwidget)
        self.logo.setGeometry(QtCore.QRect(10, 10, 131, 71))
        self.logo.setMaximumSize(QtCore.QSize(282, 160))
        self.logo.setSizeIncrement(QtCore.QSize(1, 2))
        self.logo.setText("")
        self.logo.setPixmap(QtGui.QPixmap("../../Hardis-Blockchain/logo.png"))
        self.logo.setScaledContents(True)
        self.logo.setObjectName("logo")
        self.logout = QtWidgets.QLabel(self.centralwidget)
        self.logout.setGeometry(QtCore.QRect(816, 10, 21, 21))
        self.logout.setText("")
        self.logout.setPixmap(QtGui.QPixmap("../../Hardis-Blockchain/log-out.jpg"))
        self.logout.setScaledContents(True)
        self.logout.setObjectName("logout")
        self.Enregistrer = QtWidgets.QPushButton(self.centralwidget)
        self.Enregistrer.setGeometry(QtCore.QRect(350, 190, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setItalic(False)
        self.Enregistrer.setFont(font)
        self.Enregistrer.setCursor(QtGui.QCursor(QtCore.Qt.ArrowCursor))
        self.Enregistrer.setMouseTracking(False)
        self.Enregistrer.setFlat(False)
        self.Enregistrer.setObjectName("Enregistrer")
        self.type_menu = QtWidgets.QComboBox(self.centralwidget)
        self.type_menu.setGeometry(QtCore.QRect(210, 140, 191, 31))
        self.type_menu.setObjectName("type_menu")
        self.type_menu.addItem("")
        self.type_menu.addItem("")
        self.type_menu.addItem("")
        self.type_menu.addItem("")
        self.chercher = QtWidgets.QLabel(self.centralwidget)
        self.chercher.setGeometry(QtCore.QRect(60, 140, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.chercher.setFont(font)
        self.chercher.setObjectName("chercher")
        self.valeur_entree = QtWidgets.QLineEdit(self.centralwidget)
        self.valeur_entree.setGeometry(QtCore.QRect(570, 140, 181, 31))
        self.valeur_entree.setObjectName("valeur_entree")
        self.valeur = QtWidgets.QLabel(self.centralwidget)
        self.valeur.setGeometry(QtCore.QRect(480, 140, 81, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.valeur.setFont(font)
        self.valeur.setObjectName("valeur")
        self.affichage = QtWidgets.QTextBrowser(self.centralwidget)
        self.affichage.setGeometry(QtCore.QRect(95, 250, 655, 260))
        self.affichage.setObjectName("affichage")
        Accueil.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(Accueil)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 845, 22))
        self.menubar.setObjectName("menubar")
        self.menuHardis_Materiel = QtWidgets.QMenu(self.menubar)
        self.menuHardis_Materiel.setObjectName("menuHardis_Materiel")
        self.menuEnregistrer_materiel = QtWidgets.QMenu(self.menubar)
        self.menuEnregistrer_materiel.setObjectName("menuEnregistrer_materiel")
        Accueil.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(Accueil)
        self.statusbar.setObjectName("statusbar")
        Accueil.setStatusBar(self.statusbar)
        self.actionEnregistrer_mat_riel = QtWidgets.QAction(Accueil)
        self.actionEnregistrer_mat_riel.setObjectName("actionEnregistrer_mat_riel")
        self.actionD_placer_mat_riel = QtWidgets.QAction(Accueil)
        self.actionD_placer_mat_riel.setObjectName("actionD_placer_mat_riel")
        self.actionConsulter_mat_riel = QtWidgets.QAction(Accueil)
        self.actionConsulter_mat_riel.setObjectName("actionConsulter_mat_riel")
        self.actionAccueil = QtWidgets.QAction(Accueil)
        self.actionAccueil.setObjectName("actionAccueil")
        self.actionParam_tres = QtWidgets.QAction(Accueil)
        self.actionParam_tres.setObjectName("actionParam_tres")
        self.actionQuitter = QtWidgets.QAction(Accueil)
        self.actionQuitter.setObjectName("actionQuitter")
        self.menuHardis_Materiel.addAction(self.actionAccueil)
        self.menuHardis_Materiel.addAction(self.actionParam_tres)
        self.menuHardis_Materiel.addAction(self.actionQuitter)
        self.menuEnregistrer_materiel.addAction(self.actionEnregistrer_mat_riel)
        self.menuEnregistrer_materiel.addAction(self.actionD_placer_mat_riel)
        self.menuEnregistrer_materiel.addAction(self.actionConsulter_mat_riel)
        self.menubar.addAction(self.menuHardis_Materiel.menuAction())
        self.menubar.addAction(self.menuEnregistrer_materiel.menuAction())

        self.retranslateUi(Accueil)
        QtCore.QMetaObject.connectSlotsByName(Accueil)

    def retranslateUi(self, Accueil):
        _translate = QtCore.QCoreApplication.translate
        Accueil.setWindowTitle(_translate("Accueil", "MainWindow"))
        self.Title.setText(_translate("Accueil", "<html><head/><body><p align=\"center\">Consulter le matériel enregistré</p></body></html>"))
        self.Enregistrer.setText(_translate("Accueil", "Valider"))
        self.type_menu.setItemText(0, _translate("Accueil", "Type de matériel"))
        self.type_menu.setItemText(1, _translate("Accueil", "ID"))
        self.type_menu.setItemText(2, _translate("Accueil", "Marque"))
        self.type_menu.setItemText(3, _translate("Accueil", "Personne responsable"))
        self.chercher.setText(_translate("Accueil", "Chercher par ..."))
        self.valeur.setText(_translate("Accueil", "Valeur"))
        self.menuHardis_Materiel.setTitle(_translate("Accueil", "Accueil"))
        self.menuEnregistrer_materiel.setTitle(_translate("Accueil", "Opérations"))
        self.actionEnregistrer_mat_riel.setText(_translate("Accueil", "Enregistrer matériel"))
        self.actionD_placer_mat_riel.setText(_translate("Accueil", "Déplacer matériel"))
        self.actionConsulter_mat_riel.setText(_translate("Accueil", "Consulter matériel"))
        self.actionAccueil.setText(_translate("Accueil", "Accueil"))
        self.actionParam_tres.setText(_translate("Accueil", "Paramètres"))
        self.actionQuitter.setText(_translate("Accueil", "Quitter"))

